name: Check for merge conflicts

on:
  push:
    branches:
      - master

jobs:
  check-merge-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout master branch
        run: |
          git checkout master
          git pull origin master
      - name: Check for merge conflicts
        run: |
          git fetch origin main
          git merge --no-ff --no-commit main
          if [ -n "$(git diff --name-only --diff-filter=U)" ]; then
            echo "There are merge conflicts."
            exit 1
          fi
      - name: Pull changes from master to main
        if: success()
        run: 
          git checkout main
          git pull origin master
          git push origin main
